version: '3.7'
services:
    uwgeocoder-alpine:
        build: 
            context: ./src/alpinedb
        shm_size: 2gb
        environment: 
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            GEOCODER_STATES: "${GEOCODER_STATES}"
            GEOCODER_YEAR: "${GEOCODER_YEAR}"
        ports:
            - "51005:5432"

