name: Fastbuild postgis images

on:
  push:
    branches:
    - "5-speed-up-builder"
  pull_request:
    branches:
      - "5-speed-up-builder"

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  # dynamic doesn't work, only static
  BUILD_NUM: $(date +%Y%m%d%H%M%S)
  REPOSITORY:

jobs:

  setup-postgis-states:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}

    steps:
    - id: matrix
      run: |
        echo 'value=["ak", "al", "ar", "az", "ca", "co", "ct", "dc", "de", "fl", "ga", "hi", "ia", "id", "il", "in", "ks", "ky", "la", "ma", "md", "me", "mi", "mn", "mo", "ms", "mt", "nc", "nd", "ne", "nh", "nj", "nm", "nv", "ny", "oh", "ok", "or", "pa", "ri", "sc", "sd", "tn", "tx", "ut", "va", "vt", "wa", "wi", "wv", "wy", "pr"]' >> $GITHUB_OUTPUT
    - run: |
        echo "${{ steps.matrix.outputs.value }}"

  build-postgis-states:
    runs-on: self-hosted
    needs: setup-postgis-states
    continue-on-error: true
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup-postgis-states.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v4
    - name: import BUILD_NUM from file
      run: echo "BUILD_NUM=$(cat ~/BUILD_NUM)" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: Build the postgis image
      run: docker build --shm-size 4g --load --cpu-quota $(( $(nproc --all)*100000 )) --build-arg state_var=${{ matrix.value }} uwpostgis-foundry --platform linux/amd64 --tag genoa-container-registry.washington.palantircloud.com/postgis-${{ matrix.value }}:${{ env.BUILD_NUM }}
    - name: Run Trivy CVE vulnerability scanner
      uses: aquasecurity/trivy-action@0.25.0
      with:
        image-ref: genoa-container-registry.washington.palantircloud.com/postgis-${{ matrix.value }}:${{ env.BUILD_NUM }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

