name: Build Docker Images

on:
  push:
    branches:
    - "preflight"
  pull_request:
    branches:
    - "preflight"

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

env:
  # dynamic doesn't work, only static
  BUILD_NUM: $(date +%Y%m%d%H%M%S)
  REPOSITORY: 

jobs:

  build-degauss-foundry:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: import BUILD_NUM from file
      run: echo "BUILD_NUM=$(cat ~/BUILD_NUM)" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: Build the degauss-foundry image
      run: docker build --load --cpu-quota $(( $(nproc --all)*100000 )) degauss-foundry --platform linux/amd64 --tag preflight-degauss-foundry:${{ env.BUILD_NUM }}
    - name: Run Trivy CVE vulnerability scanner
      uses: aquasecurity/trivy-action@0.25.0
      with:
        image-ref: preflight-degauss-foundry:${{ env.BUILD_NUM }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

  setup-postgis-states:
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}

    steps:
    - id: matrix
      run: |
        echo 'value=["hi"]' >> $GITHUB_OUTPUT
    - run: |
        echo "${{ steps.matrix.outputs.value }}"

  build-postgis-states:
    runs-on: self-hosted
    needs: setup-postgis-states
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup-postgis-states.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v4
    - name: import BUILD_NUM from file
      run: echo "BUILD_NUM=$(cat ~/BUILD_NUM)" >> $GITHUB_ENV
    - name: print env
      run: env
    - name: Build the postgis image
      run: docker build --shm-size 4g --load --cpu-quota $(( $(nproc --all)*100000 )) --build-arg state_var=${{ matrix.value }} uwpostgis-foundry --platform linux/amd64 --tag preflight-postgis-${{ matrix.value }}:${{ env.BUILD_NUM }}
    - name: Run Trivy CVE vulnerability scanner
      uses: aquasecurity/trivy-action@0.25.0      
      with:
        image-ref: preflight-postgis-${{ matrix.value }}:${{ env.BUILD_NUM }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

